### ISSUE TITLE
simhash.Corpus constructor hangs the program on Windows 8 

### ISSUE THREAD

**Issue by amironoff** [seomoz/simhash-py#12]
Hi,

I have managed to install simhash-py on Windows 8. However, as in #2 and #3, running simhash.Corpus(6,3) hangs the program. Here's the environment description:

1. OS: Windows 8 Enterprise, x64,
2. Python: 2.7.8, x64,
3. Cython: 0.21.2;
4. Judy - compiled with VS 12.0 C++ compiler targetting amd64. Then copied manually to Python directory;

As a side note, I had to edit Jenkins.h - removed importing "sys/param.h", then simplified determining big vs small endianness (Windows is little endian in all of my environments):

```C
 # define HASH_LITTLE_ENDIAN 1
 # define HASH_BIG_ENDIAN 0
```

**Comment by b4hand** [comment]
We have no plans of supporting simhash-py on Windows. If you can make a PR to make it work, and it doesn't break anything else, then we'll accept the PR.
