### ISSUE TITLE
test_get_all fails

### ISSUE THREAD

**Issue by eyvindn** [seomoz/simhash-py#14]
For some reason, find/find_all works well works, but calling hashes() on a corpus results in completely wrong hashes being returned. 

Running OSX 10.10.3 with Python 2.7.6, just cloned from the repo and followed the instructions. 

Could it have something to do with 64 vs 32bit when compiling, which I am getting errors about?

During compile I get a lot of these errors:

warning: implicit conversion loses integer precision: 'uint64_t' (aka 'unsigned long long') to 'Simhash::hash_t' (aka 'unsigned long') [-Wshorten-64-to-32]

**Comment by b4hand** [comment]
simhash-py has only been tested in 64-bit environments. If you're compiling it for 32-bit, you're on your own for help.

**Comment by eyvindn** [comment]
I'm not compiling in a 32-bit environment, I investigated the issue further, and setup.py simply compiles a universal binary by default. However, forcing it to only compile for x86_64 doesn't help (obviously, as it was using the 64-bit implementation in the universal binary by default)

**Comment by eyvindn** [comment]
The issue actually lies in simhash-cpp, namely the const_iterator is wrongly implemented and does not properly loop through the Judy array. I'll submit a fix.

**Comment by b4hand** [comment]
Could you please confirm that this has been fixed by pulling in recent updates from simhash-cpp in #19?

**Comment by b4hand** [comment]
I'm going to assume this was resolved with the prior PR since there's been no update on this ticket in a long while.
