### ISSUE TITLE
Conda-forge package

### ISSUE THREAD

**Issue by rth** [seomoz/simhash-py#35]
As mentionned in issue #32, it would have been useful to submit `simhash-py` to https://conda-forge.github.io/
so that it could be simply installed with
```
conda install -c conda-forge simhash-py
```
without the need to compile the C++ code. 

Once a Pull Request with the setup is submitted at https://github.com/conda-forge/staged-recipes and accepted, it would create a repository https://github.com/conda-forge/simhash-py-feedstock that would have to be updated for every new release. This should allow to create a pre-built Python package for Linux and possibly Mac OS (Windows won't install won't be available for now cf #31 ). The questions I was wondering about are,
   * who should make that PR submission (I can do it, if necessary)
   * who should be added to the maintainers of that `conda-forge/simhash-py-feedstock` setup ? 
   * there is still the naming issue, discussed in issue #32, the package would be called `simhash-py` but would be imported as `simhash`, since the `simhash` package already exist at https://github.com/conda-forge/simhash-feedstock . Not sure if there is a better way of doing it?

@b4hand What do you think?

**Comment by b4hand** [comment]
Let me discuss the naming concern with a few devs here, and I'll try to see what we can do.

**Comment by rth** [comment]
I made a request to create a `simhash-py` conda-forge package ( https://github.com/conda-forge/staged-recipes/pull/2656 ) which would be imported as `import simhash`. Please let me know if you want to change the package name or if someone form SeoMoz should be added to the list of maintainers there (which can always be done later).. Thank you.

**Comment by rth** [comment]
The conda-forge setup for simhash-py was created at https://github.com/conda-forge/simhash-py-feedstock

simhash-py 4.0.0 can now be installed for Python 2.7, 3.5, 3.6 on Linux and MacOS using [conda](https://conda.io/docs/) with,

```
conda config --append channels conda-forge
conda install simhash-py
```
which does not require Cython or a C++ compiler.
