### ISSUE TITLE
Create PyPi release

### ISSUE THREAD

**Issue by b4hand** [seomoz/simhash-py#36]
As brought up in #32, we should have a public pypi release available.

However, there's already a pypi package called `simhash`, but historically, this project has used `import simhash` despite the name conflict.

I'm not sure how much of a problem it is to have the package name differ from the module name, but we should figure out some way to get this published. That may involve renaming the package, if necessary.

**Comment by rth** [comment]
@b4hand I was wondering if anything was decided regarding the Python package name? 

I think changing the module name is a significant backward incompatible change, that might be a larger issue to the users than the possible name conflict with the other simhash package on Pypi. 

It's also possible to have a package on pypi `simhash-py`, installed as,
```
pip install simhash-py
```
than is then imported as `import simhash` ...

**Comment by b4hand** [comment]
Sorry for the delay, I've been busy with several other projects. I've gone ahead and created a new 0.4.0 simhash-py distribution on pypi. Technically, #39 has not been merged yet, but the package is now already available.
